
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
  labels:
    app: health-deployment
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: health-pod
  template:
    metadata:
      labels:
        app: health-pod
        owner: vitshevl
    spec:
      containers:
      - name: health-container
        image: vitshevl/health-service:1.0.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  selector:
    app: health-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
