apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment-new
  labels:
    app: health-deployment-new
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: health-pod-new
  template:
    metadata:
      labels:
        app: health-pod-new
        owner: vitshevl
    spec:
      containers:
        - name: health-container
          image: vitshevl/health-service:3.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5  
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1  
            failureThreshold: 5