
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: proxy-pod
  template:
    metadata:
      labels:
        app: proxy-pod
        owner: vitshevl
    spec:
      containers:
      - name: proxy-container
        image: vitshevl/proxy-service:1.0.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
