apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
  labels:
    app: health-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: health-pod
  template:
    metadata:
      labels:
        app: health-pod
        owner: vitshevl
    spec:
      containers:
        - name: health-container
          image: vitshevl/health-service:2.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1  
---

apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  selector:
    app: health-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080